package api

import (
	"fmt"
	"log"
	"strings"

	"github.com/sagan/goaider/features/llm"
)

// jsonschema is parsed by https://github.com/invopop/jsonschema

// Creative Lists generated by LLM, they are suitable for used as input of ComfyUI text-2-image workflow.
// Contain lists of actions and contexts in English and Simplified Chinese.
type CreativeLists struct {
	// action examples: chasing bubbles, reading a giant book, riding a tiger
	Actions   []string `json:"actions" jsonschema:"description=A list of creative activities or poses."`
	ActionsZh []string `json:"actions_zh" jsonschema:"description=The Simplified Chinese translation of actions"`
	// context example: Ghibli style meadow
	Contexts   []string `json:"contexts" jsonschema:"description=A list of detailed visual environments and art styles."`
	ContextsZh []string `json:"contexts_zh" jsonschema:"description=The Simplified Chinese translation of contexts"`
}

func GenerateActionList(apiKey, model, subject string, theme string, temperature float64) (*CreativeLists, error) {
	if subject == "" {
		subject = "a person"
	}

	paragraphes := []string{
		fmt.Sprintf(`I am generating AI images and videos of a subject. The subject is %s.`, subject),

		`I need two lists to combine later:
1. 'actions': A list of 50 distinct, imaginative actions suitable for the subject (e.g., chasing bubbles, reading a giant book, riding a tiger).
2. 'contexts': A list of 50 distinct visual styles/environments (e.g., Ghibli style meadow, Cyberpunk street, Watercolor dream).`,
	}

	if theme != "" {
		paragraphes = append(paragraphes, fmt.Sprintf(
			"The theme is %s. The generated lists of actions & contexts need to be consistent with this theme.",
			theme))
	}

	paragraphes = append(paragraphes,
		`Additionally, output two more lists:
- 'actions_zh' list: that's the Simplified Chinese translation of 'actions' list. The 'actions' list and 'actions_zh' list must have the same length.
- 'contexts_zh' list: that's the Simplified Chinese translation of 'contexts' list. The 'contexts' list and 'contexts_zh' list must have the same length.`,

		`Be creative. Ensure variety in lighting, atmosphere, and activity.`,
	)

	prompt := strings.Join(paragraphes, "\n\n")

	log.Printf("Use %s model; prompt: %s", model, prompt)
	return llm.ChatJsonResponse[CreativeLists](apiKey, model, prompt, temperature)
}
