package all

import (
	_ "github.com/sagan/goaider/cmd/base64decode"
	_ "github.com/sagan/goaider/cmd/base64encode"
	_ "github.com/sagan/goaider/cmd/caption"
	_ "github.com/sagan/goaider/cmd/chat"
	_ "github.com/sagan/goaider/cmd/comfyui/all"
	_ "github.com/sagan/goaider/cmd/copy"
	_ "github.com/sagan/goaider/cmd/crop"
	_ "github.com/sagan/goaider/cmd/csv/all"
	_ "github.com/sagan/goaider/cmd/extractall"
	_ "github.com/sagan/goaider/cmd/findfiles"
	_ "github.com/sagan/goaider/cmd/indexfiles"
	_ "github.com/sagan/goaider/cmd/jq"
	_ "github.com/sagan/goaider/cmd/mediainfo"
	_ "github.com/sagan/goaider/cmd/norfilenames"
	_ "github.com/sagan/goaider/cmd/parsetfef"
	_ "github.com/sagan/goaider/cmd/paste"
	_ "github.com/sagan/goaider/cmd/rand"
	_ "github.com/sagan/goaider/cmd/randb"
	_ "github.com/sagan/goaider/cmd/randu"
	_ "github.com/sagan/goaider/cmd/sha256sum"
	_ "github.com/sagan/goaider/cmd/sovits-genlist"
	_ "github.com/sagan/goaider/cmd/structdiff"
	_ "github.com/sagan/goaider/cmd/stt"
	_ "github.com/sagan/goaider/cmd/translate"
)
