package randb

import (
	"encoding/base64"
	"fmt"
	"os"

	"github.com/sagan/goaider/cmd"
	"github.com/sagan/goaider/util"
	"github.com/spf13/cobra"
	"golang.org/x/term"
)

var randCmd = &cobra.Command{
	Use:     "randb",
	Aliases: []string{"randombytes"},
	Short:   "Get a cryptographically secure randam bytes of length 16. Output base64 by default",
	Long: `Get a cryptographically secure randam bytes of length 16. Output base64 by default.

It outputs to stdout.`,
	RunE: doRandb,
}

var (
	flagHex    bool // output hex string
	flagRaw    bool // output raw binary
	flagUrl    bool // output in URL-safe BASE64 (without padding) encoding instead of standard base64
	flagLength int  // length of generated bytes. default to 16.
)

func doRandb(cmd *cobra.Command, args []string) error {
	if util.CountNonZeroVariables(flagHex, flagRaw, flagUrl) > 1 {
		return fmt.Errorf("only one of --hex, --raw, --url can be set")
	}
	b := util.RandBytes(flagLength)
	if flagRaw {
		if term.IsTerminal(int(os.Stdout.Fd())) {
			return fmt.Errorf("stdout is tty. use --raw only when redirecting to a file or piping to another command")
		}
		os.Stdout.Write(b)
	} else if flagHex {
		fmt.Printf("%x", b)
	} else if flagUrl {
		fmt.Print(base64.URLEncoding.WithPadding(base64.NoPadding).EncodeToString(b))
	} else {
		fmt.Print(base64.StdEncoding.EncodeToString(b))
	}
	return nil
}

func init() {
	randCmd.Flags().BoolVarP(&flagHex, "hex", "x", false, "Output hex string")
	randCmd.Flags().BoolVarP(&flagRaw, "raw", "r", false, "Output raw binary")
	randCmd.Flags().BoolVarP(&flagUrl, "url", "u", false,
		"Output in URL-safe BASE64 (without padding) encoding instead of standard base64")
	randCmd.Flags().IntVarP(&flagLength, "length", "l", 16, "Length of the random bytes")
	cmd.RootCmd.AddCommand(randCmd)
}
